allure.results.directory=target/allure-results
allure.link.issue.pattern=https://github.com/kaluhele/QA-Automation-Challenge-BackEnd/issues/{}
allure.link.tms.pattern=https://github.com/kaluhele/QA-Automation-Challenge-BackEnd/{}

